version: '3.5'
services:
  app:
    container_name: 'app'
    image: php-nginx-alpine
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=local
      - VIRTUAL_HOST=localhost
      - SERVER_ALIAS=localhost
      - SERVER_ROOT=/var/www/html
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    healthcheck:
      test: ['CMD-SHELL', 'curl -f -s http://localhost/health-check || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3