version: '3.5'
services:
  app:
    container_name: 'app'
    image: engineroom/email-service
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    environment:
      - APP_ENV=local
      - VIRTUAL_HOST=localhost
      - SERVER_ALIAS=localhost
      - SERVER_ROOT=/var/www/html
      - MY_ENV=Thilanga
      - I_SEE_CRON=CronCANSeeThis
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    healthcheck:
      test: ['CMD-SHELL', 'curl -f -s http://localhost/health-check || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
