#!/usr/bin/env sh

ENV_FILE=/etc/envvars
if test -f "${ENV_FILE}"; then
    source /etc/envvars
fi

exec 2>&1

DAEMON=/usr/local/sbin/php-fpm

PID_FILE=/run/php-fpm/php-fpm.pid
# Create pid file's directory
install -d -o www-data -g www-data ${PID_FILE%/*}

# set fpm process numbers
/auto-fpm.sh >&2

test -x ${DAEMON} || (echo 'php-fpm has not installed.' && exit 1)
${DAEMON} --test || (echo 'php-fpm config has error.' && exit 1)

exec ${DAEMON} --nodaemonize